---
title: "3_EnrichmentAroundFeatures"
output: html_document
date: "2025-08-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries}
library(dplyr)
library(stringr)
library(patchwork)
library(EnrichedHeatmap)
library(ggplot2)
library(readr)
library(data.table)
```

```{r Setting Paths}
#R_Data <- "/home/ocdm0351/DPhil/R_Data/" # For HPC
R_Data <- "/home/dan/DPhil/MA_Project_1/R_Data/" # For HPC

#Species_Data <- "/home/ocdm0351/.conda/envs/snpEff/share/snpeff-5.2-2/data/" # For HPC
Species_Data <- "/home/dan/DPhil/MA_Project_1/R_Data/data/" # For Laptop

```

```{r Loading Annotated VCF List}
load(file = paste0(R_Data, "Annotated_VCFs_Raw"))
load(file = paste0(R_Data, "Annotated_VCFs_PC_Gene_Body_Variants"))

# Subset to just Drosophila for testing
Annotated_VCFs_PC_Gene_Body_Variants <- Annotated_VCFs_PC_Gene_Body_Variants[names(Annotated_VCFs_PC_Gene_Body_Variants) %like%
                                                                      "Dmelanogaster" |
                                                                     # names(Annotated_VCFs_PC_Gene_Body_Variants) %like%
                                                                    #  "Hsapiens" |
                                                                       names(Annotated_VCFs_PC_Gene_Body_Variants) %like%
                                                                      "Celegans" |
                                                                       names(Annotated_VCFs_PC_Gene_Body_Variants) %like%
                                                                      "Ppacificus"]


source(paste0(R_Data, "plotting.themes.R"))
# Choose theme once per session/script
set_my_theme("light")   # or "dark"
```

```{r Reduced to Unique Variants}
Reduced_Variants <- lapply(Annotated_VCFs_Raw, 
                           function(df) df[, 1:4] %>% unique() %>% select(-c("REF","ALT")))
```

```{r Enriched Heatmap}
# I think how this is going to work is we need some summary file. 
# Needs to link the list element (file) to its reference file path, to first load it in. 
# In the loop or function, it will do the following, for each element:
  # 1. Load in the correct reference file. 
  # 2. Get start/end positions for all genes (protein coding and otherwise) and make into GRanges.
  # 3. Keep the biotype handy, as we will try to subset the EnrichedHeatmap to show them independently. 
  # 4. Generate EnrichedHeatmap by intersecting variants and gene body coordinates and save into folder.

MutationDensityPlots <- list()

lapply(names(Reduced_Variants), function(element_name) {

  # Step One: Isolate Components of Path to Load Reference Build(s)
  element <- Reduced_Variants[[element_name]] # Get the element data
  build <- str_split(element_name, "_", simplify = TRUE)[,5] # Isolate just the build (is a sub-directory in species folder)
  species <- str_split(element_name, "_", simplify = TRUE)[,4] %>% str_replace(., "^(.)(.*)$", "\\1_\\2")
  speciesANDbuild <- paste(species, build, sep = "_") 
  
  # Step Three: Convert Variants into GRanges Object (Required for EnrichedHeatmap)
  variant_ranges <-
  makeGRangesFromDataFrame(element,
                           keep.extra.columns=TRUE,
                           ignore.strand=TRUE,
                           seqnames.field=c("CHROM"),
                           na.rm = TRUE,
                           start.field="POS",
                           end.field=c("POS"),
                           strand.field="strand",
                           starts.in.df.are.0based=FALSE)
  
  variant_ranges <- coverage(variant_ranges)
  # keep only non-zero coverage runs
  variant_ranges <- as(variant_ranges, "GRanges")
  variant_ranges <- variant_ranges[variant_ranges$score > 0]
  
  
  # Step Four: Intersect Variant and Gene Body Ranges Annoted into Groups! and Plot Enrichment Using EnrichedHeatmap
  # Selecting Parameters
  annotated_element <- Annotated_VCFs_PC_Gene_Body_Variants[[element_name]] # Get the element data
  
  annotated_element_ranges <-
  makeGRangesFromDataFrame(annotated_element[, c("CHROM","start","end",
                                                  "GENE_ID",
                                                 "Overall_Expression_Group",
                                                 "Overall_dNdS_Group",
                                                 "Overall_Mutation_Rate_Group")] %>% 
                           unique(),
                           keep.extra.columns=TRUE,
                           ignore.strand=TRUE,
                           seqnames.field=c("CHROM"),
                           na.rm = TRUE,
                           start.field="start",
                           end.field=c("end"),
                           strand.field="strand",
                           starts.in.df.are.0based=FALSE)
  
  # Set Up Testing Params
  Parameters <- data.frame(mean_mode_type = c("w0","w0","w0","w0","w0","w0",
                                          "absolute","absolute","absolute","absolute","absolute","absolute",
                                          "weighted","weighted","weighted","weighted","weighted","weighted",
                                          "coverage","coverage","coverage","coverage","coverage","coverage"),
                       extend_value = c(5000,5000,5000,5000,5000,5000,
                                        5000,5000,5000,5000,5000,5000,
                                        5000,5000,5000,5000,5000,5000,
                                        5000,5000,5000,5000,5000,5000),
                       window = c(10,25,50,10,25,50,
                                  10,25,50,10,25,50,
                                  10,25,50,10,25,50,
                                  10,25,50,10,25,50)) %>% unique()
                       
#  Parameters <- subset(Parameters, 
#  mean_mode_type == "absolute" &
#  window == 50 &
#  genes == "protein.coding.genes.gtf")

  for (row in 1:nrow(Parameters)){
        #gene_type <- Parameters[row,"genes"]
        mean_mode_type <- Parameters[row,"mean_mode_type"]
        window <- Parameters[row,"window"]
        extend_value <- Parameters[row,"extend_value"]
        mean_mode_type <- Parameters[row,"mean_mode_type"]
        #target_ratio_value <- .6
  
body_mutation_enrichment <- normalizeToMatrix(variant_ranges,
                                             annotated_element_ranges,
                                             extend = extend_value,
                                             mean_mode = mean_mode_type,
                                             w = window,
                                             target_ratio = .7,
                                             smooth = TRUE,
                                             background = 0)
  
    #test <-
    #EnrichedHeatmap(body_epi_enrichment, name = "H3K9me3",
    # top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = 2:4))),
    # column_title = "H3K9me3",
    # row_split = gene_gr$mut_Group)

    # Extract Enrichment Bins and Grouping Indexing Information
    mat <- as.matrix(body_mutation_enrichment)
    groups <- as.factor(annotated_element_ranges$Overall_Expression_Group)
    # Combine into a tidy data frame
    df <- as.data.frame(mat) %>%
      mutate(Overall_Expression_Group = groups) %>%
      tidyr::pivot_longer(cols = -c(Overall_Expression_Group), names_to = "position", values_to = "value") %>%
      mutate(position = as.numeric(factor(position, levels = colnames(mat))))
    
    # Remove NA group loci
    df <- subset(df, is.na(Overall_Expression_Group) == FALSE)
    
    # Summarise by dNdS group (mean + SE per position)
    MutationDensities <- df %>%
      group_by(Overall_Expression_Group, position) %>%
      summarise( mean_score = mean(value, na.rm = TRUE), se = sd(value, na.rm = TRUE) / sqrt(n()), .groups = "drop")

    # --- keep your original boundary logic exactly ---
    avg <- colMeans(mat)
    regionLength <- ((0.7 * 100) * length(avg)) / 100
    lengthEachSide <- (length(avg) - regionLength) / 2
    start <- lengthEachSide
    end <- length(avg) - lengthEachSide
    # Renaming NA dNdS Group
    #MutationDensities <- MutationDensities %>% mutate(dNds_Group = forcats::fct_explicit_na(group, na_level = "No Ortholog"))

    # --- Plot grouped by dNdS version ---
      MutationDensityPlot <-
      ggplot(MutationDensities,
             aes(x = position, y = mean_score, color = Overall_Expression_Group, fill = Overall_Expression_Group)) +
      geom_line(size = .5) +
      geom_ribbon(aes(ymin = mean_score - se, ymax = mean_score + se),
              alpha = 0.2, color = NA) +
      geom_vline(xintercept = c(start, end), linetype = "dotted") +
      theme_bw() +
      labs(
      title = paste(element_name,"\n",
                  "Mutational Frequency Around Gene Bodies: Window Size =", window,
                  "Mean Mode =", mean_mode_type,
                  "Extended =", extend_value),
      color = "Expression Quantile",
      fill = "Expression Quantile") +
      theme_bw() +
    
          scale_x_continuous(n.breaks = 10) +
          scale_y_continuous(n.breaks = 10)

          # ggSaving
          ggsave(MutationDensityPlot,
             filename = paste0(R_Data, 
                               "Plots/2_GeneBody_Plots/",
                               mean_mode_type, "/GeneBodyOnly_", 
                               element_name, "_", window, "_Peaks", "byExpression",".png"),
             bg = "transparent",
             type="cairo",
             units = "cm",
             height = 8,
             width = 15,
             create.dir = TRUE,
             dpi = 2000)
    
  
  # Save Plot into List for Combining
  MutationDensityPlots[[element_name]] <<- MutationDensityPlot
}
})

```
