---
title: "MutationRate_Functional_Enrichment"
output: html_document
date: "2026-04-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries}
suppressPackageStartupMessages({
  library(tidyverse)
  library(ggplot2)
  library(data.table)
  library(mgcv)
  library(segmented)
  library(clinfun)
  library(clusterProfiler)
  library(enrichplot)
  library(patchwork)
  library(AnnotationDbi)
  library(GO.db)
  library(org.Ce.eg.db)
  library(org.Dm.eg.db)
  library(biomaRt)
  library(dplyr)
  library(readr)
  library(stringr)
})

`%ni%` <- Negate(`%in%`)
```

```{r Setting Paths}
R_Data <- "/home/ocdm0351/DPhil/R_Data/" # For HPC
#R_Data <- "/home/dan/DPhil/MA_Project_1/R_Data/" # For Laptop
Species_Data <- "/home/ocdm0351/.conda/envs/snpEff/share/snpeff-5.2-2/data/" # For HPC
#Species_Data <- "/home/dan/DPhil/MA_Project_1/R_Data/data/" # For Laptop

```

```{r Loading Data}
load(file = paste0(R_Data, "Annotated_VCFs_PC_Gene_Body_Variants"))
```

```{r New Method Test}
options(timeout = 300)

GO_Annotation_Dir <- file.path(R_Data, "GO_Annotations")
dir.create(GO_Annotation_Dir, recursive = TRUE, showWarnings = FALSE)

get_go_table_biomart <- function(dataset, mart) {
  message("Downloading GO annotations for ", dataset)

  m <- useDataset(dataset, mart)

  x <- getBM(
    attributes = c(
      "ensembl_gene_id",
      "go_id",
      "namespace_1003",
      "name_1006"
    ),
    mart = m
  )

  colnames(x) <- c("gene_id", "go_id", "ontology", "go_name")

  x %>%
    filter(
      !is.na(gene_id),
      gene_id != "",
      !is.na(go_id),
      go_id != ""
    ) %>%
    distinct()
}

get_go_table_orgdb <- function(orgdb, keytype) {
  message("Using local OrgDb fallback for keytype: ", keytype)

  x <- AnnotationDbi::select(
    orgdb,
    keys = keys(orgdb, keytype = keytype),
    columns = c("GO", "ONTOLOGY"),
    keytype = keytype
  )

  colnames(x)[colnames(x) == keytype] <- "gene_id"
  colnames(x)[colnames(x) == "GO"] <- "go_id"
  colnames(x)[colnames(x) == "ONTOLOGY"] <- "ontology"

  x <- x %>%
    filter(
      !is.na(gene_id),
      gene_id != "",
      !is.na(go_id),
      go_id != ""
    ) %>%
    distinct()

  go_names <- AnnotationDbi::select(
    GO.db,
    keys = unique(x$go_id),
    columns = c("TERM"),
    keytype = "GOID"
  ) %>%
    dplyr::rename(
      go_id = GOID,
      go_name = TERM
    ) %>%
    distinct()

  dplyr::left_join(x, go_names, by = "go_id")
}

try_mart <- function(biomart, hosts) {
  for (h in hosts) {
    message("Trying ", biomart, " at ", h)
    m <- tryCatch(
      useEnsemblGenomes(biomart = biomart, host = h),
      error = function(e) NULL
    )
    if (!is.null(m)) return(m)
  }

  NULL
}

resolve_go_annotations <- function(sp, info) {
  outfile <- file.path(GO_Annotation_Dir, paste0(sp, "_GO.tsv"))

  cached_go <- NULL
  if (file.exists(outfile)) {
    message("Found cached GO annotations for ", sp)
    cached_go <- read_tsv(outfile, show_col_types = FALSE)
  }

  mart <- try_mart(info$biomart, info$hosts)

  if (!is.null(mart)) {
    live_go <- tryCatch(
      get_go_table_biomart(info$dataset, mart),
      error = function(e) {
        message("BioMart failed for ", sp, ": ", e$message)
        NULL
      }
    )

    if (!is.null(live_go) && nrow(live_go) > 0) {
      write_tsv(live_go, outfile)
      return(live_go)
    }
  }

  if (!is.null(cached_go) && nrow(cached_go) > 0) {
    message("Using cached GO annotations for ", sp)
    return(cached_go)
  }

  fallback_go <- get_go_table_orgdb(info$orgdb, info$keytype)
  write_tsv(fallback_go, outfile)
  fallback_go
}

species_datasets <- list(
  Celegans = list(
    dataset = "celegans_eg_gene",
    biomart = "metazoa_mart",
    hosts = c(
      "https://metazoa.ensembl.org",
      "https://eg63-metazoa.ensembl.org"
    ),
    orgdb = org.Ce.eg.db,
    keytype = "WORMBASE"
  ),
  Dmelanogaster = list(
    dataset = "dmelanogaster_eg_gene",
    biomart = "metazoa_mart",
    hosts = c(
      "https://metazoa.ensembl.org",
      "https://eg63-metazoa.ensembl.org"
    ),
    orgdb = org.Dm.eg.db,
    keytype = "FLYBASE"
  )
)

GO_Annotations <- setNames(
  lapply(
    names(species_datasets),
    function(sp) resolve_go_annotations(sp, species_datasets[[sp]])
  ),
  names(species_datasets)
)

for (sp in names(GO_Annotations)) {
  message(
    sp,
    ": ",
    nrow(GO_Annotations[[sp]]),
    " GO annotations"
  )
}

saveRDS(
  GO_Annotations,
  file = file.path(R_Data, "GO_Annotations.rds")
)

message(
  "Saved GO_Annotations to: ",
  file.path(R_Data, "GO_Annotations.rds")
)
```


```{r Test New Method Part Two}
GO_GSEA_Results <- list()

GO_GSEA_Plot_Dir <- file.path(
  R_Data,
  "Plots/3_Mutation_and_dNdS_Association_Plots/GO_GSEA_MutationRate"
)
dir.create(GO_GSEA_Plot_Dir, recursive = TRUE, showWarnings = FALSE)

ont_lookup <- c(
  BP = "biological_process",
  MF = "molecular_function",
  CC = "cellular_component"
)

for (element_name in names(Annotated_VCFs_PC_Gene_Body_Variants)) {

  df <- Annotated_VCFs_PC_Gene_Body_Variants[[element_name]] %>%
    distinct(GENE_ID, .keep_all = TRUE) %>%
    filter(!is.na(GENE_ID), !is.na(UniqueVariantsPlusOnePerBP))

  if (nrow(df) < 10) next

  if (grepl("Celegans|C_elegans", element_name, ignore.case = TRUE)) {
    species_tag <- "Celegans"
  } else if (grepl("Dmelanogaster|D_melanogaster", element_name, ignore.case = TRUE)) {
    species_tag <- "Dmelanogaster"
  } else {
    next
  }

  if (is.null(GO_Annotations[[species_tag]]) || nrow(GO_Annotations[[species_tag]]) == 0) {
    next
  }

  message("Running GO GSEA for: ", element_name)

  geneList <- log10(df$UniqueVariantsPlusOnePerBP)
  names(geneList) <- df$GENE_ID
  geneList <- sort(geneList, decreasing = TRUE)

  species_out_dir <- file.path(
    GO_GSEA_Plot_Dir,
    species_tag
  )

  dir.create(
    species_out_dir,
    recursive = TRUE,
    showWarnings = FALSE
  )

  res_all <- list()

  for (ont in c("BP", "MF", "CC")) {

    go_subset <- GO_Annotations[[species_tag]] %>%
      filter(
        ontology == ont_lookup[[ont]]
      )

    TERM2GENE <- unique(
      go_subset[, c("go_id", "gene_id")]
    )

    TERM2NAME <- unique(
      go_subset[, c("go_id", "go_name")]
    )

    if (nrow(TERM2GENE) == 0) next

    gsea_res <- tryCatch(

      clusterProfiler::GSEA(
        geneList = geneList,
        TERM2GENE = TERM2GENE,
        TERM2NAME = TERM2NAME,
        by = "fgsea",
        minGSSize = 5,
        maxGSSize = 500,
        pvalueCutoff = 1,
        verbose = FALSE,
        seed = TRUE
      ),

      error = function(e) {

        message(
          "GSEA failed for ",
          element_name,
          " (",
          ont,
          "): ",
          e$message
        )

        return(NULL)

      }

    )

    if (is.null(gsea_res)) next

    gsea_df <- as.data.frame(gsea_res)

    if (nrow(gsea_df) == 0) next

    gsea_df <- gsea_df %>%
      mutate(
        species_experiment = element_name,
        species = species_tag,
        ontology = ont
      )

    res_all[[ont]] <- gsea_df

    write_tsv(
      gsea_df,
      file.path(
        species_out_dir,
        paste0(
          element_name,
          "_",
          ont,
          "_gsea.tsv"
        )
      )
    )

    # ----------------------------
    # BARPLOT
    # ----------------------------

    plot_df <- gsea_df %>%
      arrange(
        p.adjust,
        desc(abs(NES))
      ) %>%
      slice_head(n = 18) %>%
      mutate(
        Description = factor(
          Description,
          levels = Description[order(NES)]
        )
      )

    if (nrow(plot_df) > 0) {

      p_bar <- ggplot(
        plot_df,
        aes(
          x = Description,
          y = NES,
          fill = NES
        )
      ) +
        geom_col(width = 0.7) +
        coord_flip() +
        scale_fill_gradient2(
          low = "#006600",
          mid = "white",
          high = "orange"
        ) +
        labs(
          title = paste0(
            species_tag,
            " ",
            ont,
            " GO GSEA"
          ),
          x = NULL,
          y = "Normalized Enrichment Score (NES)"
        ) +
        theme_bw()

      ggsave(
        plot = p_bar,
        filename = file.path(
          species_out_dir,
          paste0(
            element_name,
            "_",
            ont,
            "_gsea_NES_barplot.png"
          )
        ),
        width = 8,
        height = 5,
        dpi = 800,
        bg = "transparent"
      )
    }

    # ----------------------------
    # ENRICHMENT CURVES
    # ----------------------------

    top_ids <- gsea_df %>%
      arrange(p.adjust) %>%
      pull(ID) %>%
      head(3)

    if (length(top_ids) > 0) {

      enrich_plots <- lapply(
        top_ids,
        function(id) {

          tryCatch(

            enrichplot::gseaplot2(
              gsea_res,
              geneSetID = id,
              subplots = 1:3
            ),

            error = function(e) NULL

          )

        }
      )

      enrich_plots <- Filter(
        function(x)
          inherits(x, "ggplot") ||
          inherits(x, "gtable"),
        enrich_plots
      )

      if (length(enrich_plots) > 0) {

        p_enrich <- if (length(enrich_plots) == 1) {

          enrich_plots[[1]]

        } else {

          patchwork::wrap_plots(
            enrich_plots,
            ncol = 1
          )

        }

        ggsave(
          plot = p_enrich,
          filename = file.path(
            species_out_dir,
            paste0(
              element_name,
              "_",
              ont,
              "_gsea_enrichment_plots.png"
            )
          ),
          width = 8,
          height = 4 * length(enrich_plots),
          dpi = 800,
          bg = "transparent"
        )
      }
    }
  }

  GO_GSEA_Results[[element_name]] <- res_all
}
```


```{r GO_GSEA_MutationRate_Celegans_Dmel, eval=FALSE, include=FALSE}
suppressPackageStartupMessages({
  library(clusterProfiler)
  library(enrichplot)
  library(AnnotationDbi)
  library(org.Ce.eg.db)
  library(org.Dm.eg.db)
  library(dplyr)
  library(stringr)
  library(ggplot2)
  library(patchwork)
  library(readr)
})

GO_GSEA_Results <- list()

GO_GSEA_Plot_Dir <- file.path(
  R_Data,
  "Plots/3_Mutation_and_dNdS_Association_Plots/GO_GSEA_MutationRate"
)
dir.create(GO_GSEA_Plot_Dir, recursive = TRUE, showWarnings = FALSE)

for (element_name in names(Annotated_VCFs_PC_Gene_Body_Variants)) {

  if (!grepl("Celegans|C_elegans|Dmelanogaster|D_melanogaster", element_name, ignore.case = TRUE)) next

  df <- Annotated_VCFs_PC_Gene_Body_Variants[[element_name]] %>%
    distinct(GENE_ID, .keep_all = TRUE) %>%
    filter(!is.na(GENE_ID), !is.na(UniqueVariantsPlusOnePerBP))

  if (nrow(df) < 10) next

  if (grepl("Celegans|C_elegans", element_name, ignore.case = TRUE)) {
    orgdb <- org.Ce.eg.db
    keytype_used <- "WORMBASE"
    species_tag <- "Celegans"
  } else {
    orgdb <- org.Dm.eg.db
    keytype_used <- "FLYBASE"
    species_tag <- "Dmelanogaster"
  }

  message("Running GO GSEA for: ", element_name)

  geneList <- log10(df$UniqueVariantsPlusOnePerBP)
  names(geneList) <- df$GENE_ID
  geneList <- sort(geneList, decreasing = TRUE)

  species_out_dir <- file.path(GO_GSEA_Plot_Dir, species_tag)
  dir.create(species_out_dir, recursive = TRUE, showWarnings = FALSE)

  res_all <- list()

  for (ont in c("BP", "MF", "CC")) {

    gsea_res <- tryCatch(
      gseGO(
        geneList = geneList,
        OrgDb = orgdb,
        keyType = keytype_used,
        ont = ont,
        by = "fgsea",
        minGSSize = 5,
        maxGSSize = 500,
        pvalueCutoff = 1,
        verbose = FALSE,
        seed = TRUE
      ),
      error = function(e) {
        message("GSEA failed for ", element_name, " (", ont, "): ", e$message)
        return(NULL)
      }
    )

    if (is.null(gsea_res)) next

    gsea_df <- as.data.frame(gsea_res)
    if (nrow(gsea_df) == 0) next

    gsea_df <- gsea_df %>%
      mutate(
        species_experiment = element_name,
        species = species_tag,
        ontology = ont
      )

    res_all[[ont]] <- gsea_df

    write_tsv(
      gsea_df,
      file.path(species_out_dir, paste0(element_name, "_", ont, "_gseGO.tsv"))
    )

    plot_df <- gsea_df %>%
      arrange(p.adjust, desc(abs(NES))) %>%
      slice_head(n = 18) %>%
      mutate(Description = factor(Description, levels = Description[order(NES)]))

    if (nrow(plot_df) > 0) {

      p_bar <- ggplot(plot_df, aes(x = Description, y = NES, fill = NES)) +
        geom_col(width = 0.7) +
        coord_flip() +
        scale_fill_gradient2(low = "#006600", mid = "white", high = "orange") +
        labs(
          title = paste0(species_tag, " ", ont, " GO GSEA"),
          x = NULL,
          y = "Normalized Enrichment Score (NES)"
        ) +
        theme_bw()

      ggsave(
        plot = p_bar,
        filename = file.path(
          species_out_dir,
          paste0(element_name, "_", ont, "_gseGO_NES_barplot.png")
        ),
        width = 8,
        height = 5,
        dpi = 800,
        bg = "transparent"
      )
    }

    top_ids <- head(gsea_df$ID, 3)

    if (length(top_ids) > 0) {

      enrich_plots <- lapply(top_ids, function(id) {
        tryCatch(
          enrichplot::gseaplot2(
            gsea_res,
            geneSetID = id,
            subplots = 1:3
          ),
          error = function(e) NULL
        )
      })

      enrich_plots <- Filter(
        function(x) inherits(x, "ggplot") || inherits(x, "gtable"),
        enrich_plots
      )

      if (length(enrich_plots) > 0) {

        p_enrich <- if (length(enrich_plots) == 1) {
          enrich_plots[[1]]
        } else {
          patchwork::wrap_plots(enrich_plots, ncol = 1)
        }

        ggsave(
          plot = p_enrich,
          filename = file.path(
            species_out_dir,
            paste0(element_name, "_", ont, "_gseGO_enrichment_plots.png")
          ),
          width = 8,
          height = 4 * length(enrich_plots),
          dpi = 800,
          bg = "transparent"
        )
      }
    }
  }

  GO_GSEA_Results[[element_name]] <- res_all
}
```

