---
title: "Wrangling_Ncrassa_Expression"
output: html_document
date: "2025-10-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# normalize_GSM2637957_local.R
# Uses local Neurospora GTF file for gene lengths

library(rtracklayer)

# 1. Paths
gtf <- load(file = "/home/dpdp/DPhil/R_Data/data/N_crassa/NC12/genes.gtf")
gtf
counts_url <- "https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2637nnn/GSM2637957/suppl/GSM2637957_wt0.NC10.htseq-count.Sense.txt.gz"
counts_file <- "GSM2637957_counts.txt.gz"

# 2. Download counts if needed
if (!file.exists(counts_file)) {
  download.file(counts_url, counts_file, mode = "wb")
}

# 3. Read counts
counts <- read.table(gzfile(counts_file), header = FALSE, sep = "\t",
                     col.names = c("gene_id", "count"))
# Remove htseq summary rows (those starting with "__")
counts <- subset(counts, !grepl("^__", gene_id))

# 4. Import GTF and extract gene lengths
gtf <- import(gtf_path)
genes <- gtf[gtf$type == "gene"]
gene_lengths <- data.frame(
  gene_id = genes$gene_id,
  length_bp = wid_

```